### ISSUE TITLE
requires eventie but does not have the dependency

### ISSUE THREAD

**Issue by Schnueggel** [metafizzy/unidragger#1]
Hello,

eventie is required but there is no dependency defined in package.json.
Instead the dependency unipointer has the dependency eventie. I don't think its good to rely on the existens of submodules even if it is made by yourself.

It breaks my browserify rework process. 

greetings Christian

**Comment by desandro** [comment]
Ah! Thanks for catching this bug. `eventie` has been added to `package.json` and `bower.json` dependencies in Unidragger v1.1.1.
