### ISSUE TITLE
flickity builds missing okayPointerDown

### ISSUE THREAD

**Issue by kapouer** [metafizzy/unidragger#5]
When doing `npm install` on a fresh flickity install, `okayPointerDown` will be missing.
unidragger should have bumped its version to 3 to avoid that.

**Comment by kapouer** [comment]
Edit: i guess the issue is somewhere else ! Changing title.

**Comment by kapouer** [comment]
Never mind, i just understood i needed to do `bower install` before build.

**Comment by desandro** [comment]
Thanks for following up.

You do have a point in that recent versions of Unidragger & Flickity were both not backward-compatible. It's hard to manage that between these projects. Sorry about the difficulty.
